-- ═══════════════════════════════════════════════════════════════════════════
-- 0029 · boardroom.upstream_runs — one row per engine run
--
-- THE ID IS GENERATED BY THE CLIENT BEFORE THE RUN STARTS. src/lib/upstream.js
-- mints a crypto.randomUUID(), POSTs it to upstream-run-background, and then
-- follows the run by polling this table for that id. The run executes in a
-- background function that ACKs with 202 long before it finishes, so the id is
-- the only handle the browser has on work it cannot await — which is why the
-- primary key is a plain uuid with no default and why the insert supplies it.
--
-- Both surfaces share the table; `surface` separates them ('nostradamus' and the
-- UPSTREAM proper) and every list read filters on it. `domain` is the subject,
-- backfilled onto the row as soon as the artifact knows it, so recentSubjects
-- can answer "what have I already looked at" without opening artifacts.
--
-- `artifact` is the whole audit trail as jsonb — the consensus map, the rejected
-- candidates, the scores, the raw evidence. It is what makes the result
-- trustworthy, so it is stored rather than recomputed, and it is written twice:
-- once mid-run by saveArtifact and once at the end by finishRun.
--
-- status/verdict/error are the three-way outcome. verdict and error are both
-- nullable and finishRun writes `|| null` for each rather than omitting them,
-- because a re-finish must be able to CLEAR the other one.
--
-- Note that both engines are PAUSED (ENGINES_PAUSED in src/lib/upstream.js and
-- the real gate in upstream-run-background.js). Nothing writes here today. The
-- rows already in it are still read by the Upstream page, which is why this table
-- is a backup target rather than an operational log.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists boardroom.upstream_runs (
  id          uuid        primary key,
  user_id     uuid        not null references auth.users(id) on delete cascade,
  surface     text        not null,
  domain      text,
  status      text        not null default 'running',
  verdict     text,
  error       text,
  artifact    jsonb,
  started_at  timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms integer
);

create index if not exists upstream_runs_user_surface_started_idx
  on boardroom.upstream_runs (user_id, surface, started_at desc);

alter table boardroom.upstream_runs enable row level security;

-- Tested by command, not by name — see the long note in 0001_app_settings.sql.
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'boardroom' and tablename = 'upstream_runs'
  ) then
    create policy "upstream_runs own rows" on boardroom.upstream_runs
      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
  end if;
end $$;

grant select, insert, update, delete on boardroom.upstream_runs to authenticated;
