-- ═══════════════════════════════════════════════════════════════════════════
-- 0037 · boardroom.guitar_sessions — what you actually practised
--
-- The one table in the Guitar tab that records something which HAPPENED. The
-- chord library, the curriculum and the seed repertoire all ship in the bundle
-- and can be regenerated by a deploy; a practice session cannot be reconstructed
-- from anything, which is why every write path to this table reads its error and
-- throws instead of resolving quietly (see the note at the top of
-- src/data/db.js), and why the panel keeps a localStorage mirror of the session
-- in progress until the row lands.
--
-- `day` IS A DATE, NOT A TIMESTAMP, AND THAT IS THE POINT OF HAVING BOTH. A
-- session that starts at 23:50 and saves at 00:10 is one sitting with a guitar.
-- Deriving the day from started_at in UTC would file an evening practice under
-- tomorrow for anyone west of Greenwich, and would break a streak once a year
-- when the clocks change. The client sends the local day it decided on; the
-- timestamps are kept alongside for duration and for ordering within a day.
--
-- `items` is the session's own record of what was worked on:
--   [{ id, name, rating: "clean"|"shaky"|"rough", bpm, seconds }]
-- It duplicates what guitar_skills (0038) derives from it, deliberately. The
-- skills table holds the CURRENT state, which is lossy by design — a strength of
-- 62 cannot tell you which sessions built it. This column is the history that
-- would otherwise be gone, and it is what a rebuild of the skill table after a
-- scheduler change would read from.
--
-- `drift_ms` is the drop-the-click drill's result when the session contained
-- one: signed milliseconds, negative early. Nullable because most sessions do
-- not run that drill, and a 0 would read as "perfectly on the beat" for every
-- session that never measured.
--
-- One reader, one index: db.loadGuitarSessions takes the newest 400 ordered by
-- day descending — a bit over a year of daily practice, which covers every
-- streak, heatmap and weekly-minutes read the tab makes.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists boardroom.guitar_sessions (
  id          uuid        primary key,
  user_id     uuid        not null references auth.users(id) on delete cascade,
  day         date        not null,
  started_at  timestamptz not null default now(),
  ended_at    timestamptz,
  minutes     integer     not null default 0,
  items       jsonb       not null default '[]'::jsonb,
  focus       text,
  drift_ms    numeric,
  note        text        not null default '',
  created_at  timestamptz not null default now()
);

create index if not exists guitar_sessions_user_day_idx
  on boardroom.guitar_sessions (user_id, day desc);

alter table boardroom.guitar_sessions enable row level security;

-- The name matches GUITAR_SETUP_SQL in src/data/guitar.js; the drop is here for
-- re-runnability (see the same note in 0015_workout_templates.sql).
drop policy if exists "own guitar_sessions" on boardroom.guitar_sessions;
create policy "own guitar_sessions" on boardroom.guitar_sessions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant select, insert, update, delete on boardroom.guitar_sessions to authenticated;
